# Generated by Django 5.2.16 on 2026-07-19 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productcreationrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCreationRequest',
        ),
    ]
